local h = love.harmony.utils or error()

local function examples()
  scenario('sine', function(wait)
    wait(.1)
    h.love_key('return')
    wait(.1)
    h.love_text('run("sine")')
    wait(.1)
    h.love_key('return')

    wait(.5)
    h.love_key('C-S-q')
    wait(.3)

    hm_done()
  end)

  scenario('turtle', function(wait)
    wait(.1)
    local rt = 'run("turtle")'
    h.love_text(rt)
    wait(.1)
    -- wait(.1)
    h.love_key('return')
    wait(.1)
    -- assert(love.state.app_state == 'running')
    h.screenshot('turtl')
    wait(.3)
    h.love_key('space')
    wait(.1)
    love.harmony.timer:script(function(wait)
      h.love_key('i')
      wait(.1)
      h.love_text('b')
      wait(.5)
      h.love_key('return')
      wait(.2)
    end)

    wait(1)
    h.love_key('C-S-q')
    wait(.1)
    hm_done()
  end)

  scenario('repl', function(wait)
    wait(.1)
    h.love_text('run("repl")')
    wait(.1)
    h.love_key('return')
    wait(.3)
    h.love_text('repl')
    wait(.3)
    h.love_key('return')

    for i = 0, 25 do
      wait(.1)
      h.love_text(string.char(i + 97))
      wait(.3)
      h.love_key('return')
    end

    wait(1)
    h.love_key('C-S-q')
    wait(.1)
    hm_done()
  end)

  scenario('valid', function(wait)
    wait(.1)
    h.love_text('run("valid")')
    wait(.1)
    h.love_key('return')
    wait(.3)
    h.love_text('repl')
    wait(.3)
    h.love_key('return')

    wait(1)
    h.love_key('C-S-q')
    wait(1)
    hm_done()
  end)
end

examples()
